### ISSUE TITLE
[BUG] Reload needed to get cart summary

### ISSUE THREAD

**Issue by TomPichaud** [escaladesports/gatsby-plugin-snipcart#1]
Hello there,

_First of all thank you for your easy Snipcart plugin._

As of today, I'm using the last version of Gatsby v1 and your plugin.
I followed this doc [https://docs.snipcart.com/getting-started/the-cart](url) to get the cart summary.

And I need to manually refresh the page to get the cart summary to update itself.

For example adding an item to the basket doesn't update the snipcart-total-items.
And If I navigate between pages, the snipcart-total-items is empty.

Any help or idea ?

Thanks

**Comment by kennedyrose** [comment]
Unfortunately, all this plugin does is add Snipcart to your Gatsby project. It would be up to the Snipcart API to dynamically update components that are created with React. Looking at the API, I'm not sure they can do this at the moment but it might be worth contacting them about it.

I actually started on a React component to update stuff like cart quantity. But it's a work in progress and might not be perfect at the moment.

https://www.npmjs.com/package/react-snipcart

**Comment by TomPichaud** [comment]
Thanks, I thought so... 👍 Thanks for your work!
