### ISSUE TITLE
<script src="null"></script>

### ISSUE THREAD

**Issue by JSNickerson** [escaladesports/gatsby-plugin-snipcart#4]
This plugin generates an erroneous 

`<script src="null"></script>`

tag in the body, which causes blocking, leading to slow site load and produces console error 

`Failed to load resource: the server responded with a status of 404 ()`

 in production and 

`Uncaught SyntaxError: Unexpected token <` 

in development.

Disabling this plugin and loading Snipcart + jQuery CDN in react helmet resolves the problem.

**Comment by Gueknow** [comment]
Hi,

I have the exact same issue on my website! [www.atelier-pascale.be](url)

It should be awesome if someone could find a solution to this.

**Comment by arhoy** [comment]
I am getting the same issue, I believe this is a bug, I am also getting a very annoying
/#!/ appended to my URL when adding item to checkout. I see this also on another developers site using Gatsby and SnipCart

Please fix this otherwise good plugin!

**Comment by JSNickerson** [comment]
Rather than use the plugin I ended up just adding the CDN links to the bottom of Gatsby’s html.js file. It works just as well.

https://www.gatsbyjs.org/docs/custom-html/

@arhoy - the hash-bang is normal behavior for snipcart and shouldn’t interfere with your sites routing or anything.

**Comment by alexismoreau** [comment]
setting 

> language: null

 into the plugin settings seems to be removing the script from the build.
```
    {
      resolve: 'gatsby-plugin-snipcart',
      options: {
        apiKey: process.env.SNIPCARD_API_KEY,
        language: null,
      },
    },

```

**Comment by Igor178** [comment]
I'm having the same issue...
