### ISSUE TITLE
Snipcart is now on V3

### ISSUE THREAD

**Issue by arhoy** [escaladesports/gatsby-plugin-snipcart#5]
Snipcart just released V3.
Are you guys going to be adding v3 as default going fwd soon?

**Comment by molebox** [comment]
Im going to make a gatsby theme for snipcart which will have v3. We could do a PR to this in the mean time. Im not sure how active the maintainer is though....

**Comment by arhoy** [comment]
Hey @molebox Not sure what you mean by PR but I have added the following into by gatsby-config.js file to make v3 work

```
    {
      resolve: 'gatsby-plugin-snipcart',
      options: {
        apiKey: process.env.SNIPCART_API,
        autopop: true,
        js: 'https://cdn.snipcart.com/themes/v3.0.0/default/snipcart.js',
        styles: 'https://cdn.snipcart.com/themes/v3.0.0/default/snipcart.css',
      },
    },
```

Hope that is helps anyone

**Comment by molebox** [comment]
> Hey @molebox Not sure what you mean by PR but I have added the following into by gatsby-config.js file to make v3 work
> 
> ```
>     {
>       resolve: 'gatsby-plugin-snipcart',
>       options: {
>         apiKey: process.env.SNIPCART_API,
>         autopop: true,
>         js: 'https://cdn.snipcart.com/themes/v3.0.0/default/snipcart.js',
>         styles: 'https://cdn.snipcart.com/themes/v3.0.0/default/snipcart.css',
>       },
>     },
> ```
> 
> Hope that is helps anyone

Yeah that works too, of course. I meant open a PR to this repo as it defaults to v2, maybe have an option for v2, v3 so you dont even have to do this. Whatevs though, cool its working for you. :)
